### ISSUE TITLE
Allow to toggle which sections to show?

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-launchpad#10]
Currently there are four sections:
- Create Empty
- Starred
- Launch Notebook
- Launch Console

The Starred section is configurable (can be shown/hidden) based on early talks in the design phase. The question is, should user be able to toggle any of them in the settings?

**Comment by kcpevey** [comment]
For myself as an end user, I'd like to hide the "Launch Console" section forever. That said, at least it can be collapsed which does help me reduce clutter.
