### ISSUE TITLE
Rename to `jupyter-launchpad`

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-launchpad#3]
`jupyterlab-new-launcher` was used as a placeholder name. Is it good enough or should we think of something different?

**Comment by dharhas** [comment]
A better name would be nice. Don't have many great ideas.

- jlab-alt-launcher
- jupyterlab-navigator

**Comment by krassowski** [comment]
A nice suggestion from @dillonroach: `jupyter-launchpad`. I think `jupyterlab-launchpad` could work well indeed.

Notes:
- there already is `jlab-enhanced-launcher` 
- jupyterlab-navigator will confuse users because when you search jupyterlab navigator you get results about Anaconda Navigator

**Comment by dharhas** [comment]
`jupyterlab-launchpad` is probably the clearest technical choice so I have a slight preference for that over `jupyter-launchpad` but both are fine.

**Comment by krassowski** [comment]
On second thought, this extension contributes a plugin for the dialogs which allows to select a kernel from a Notebook, so it is also applicable to the Notebook application, so `jupyter-launchpad` is fine too.
